---
- hosts: all
  become: true
  tasks:
    - name: Include variables files
      ansible.builtin.include_vars:
        dir: vars
        extensions:
          - 'yaml'
    - name: Add Hashicorp apt key
      ansible.builtin.apt_key:
        url: "{{ hashicorp_repository_key_url }}"
        state: present
    - name: Add Hashicorp apt repo
      ansible.builtin.apt_repository:
        repo: "deb {{ hashicorp_repository_url }} {{ ansible_distribution_release }} main"
        state: present
    - name: Add Adoptium apt key
      ansible.builtin.apt_key:
        url: "{{ adoptium_repository_key_url }}"
        state: present
    - name: Add Adoptium apt repo
      ansible.builtin.apt_repository:
        repo: "deb {{ adoptium_repository_url }}/deb {{ ansible_distribution_release }} main"
        state: present
    - name: Add Git apt repo
      ansible.builtin.apt_repository:
        repo: "ppa:git-core/ppa"
        state: present
    - name: Install development packages
      ansible.builtin.apt:
        name:
          - build-essential
          - consul
          - emacs
          - git
          - jq
          - socat
          - ssh-import-id
          - temurin-17-jdk
          - terraform
          - tree
          - vault
        state: latest
    - name: Set default WSL username
      ansible.builtin.template:
        src: wsl.conf.j2
        dest: /etc/wsl.conf
