---
- hosts: all
  tasks:
    - name: Setup symlinks
      ansible.builtin.file:
        src: "{{ item.source }}"
        dest: "{{ ansible_env.HOME }}/{{ item.target }}"
        state: link
      loop:
        - source: "$HOME/home/Documents"
          target: documents
        - source: "$HOME/home/Downloads"
          target: downloads
        - source: "/mnt/c/Users/{{ ansible_user_id }}"
          target: home
        - source: "/projects"
          target: projects
